/* 1. UI COMPONENT
2. ACTION TYPES
3. ACTION CREATORS
4. REDUCER
5. STORE



UI COMPONENT ---->  DISPATCHES AN ACTION ---> ACTION CREATORS ARE CALLED ---> BASED ON ACTION TYPE ---> REDUCER IS CALLED ---> STORE(STATE) IS UPDATED ---> STATE IS AVAILABLE TO UI COMPONENTS


*/